---
--- Generated by AndLua(https://github.com/JustLikeCheese/AndLua)
--- Created by Cheese
--- DateTime: 2025/7/7 00:07
---

require "import"
import "android.os.Environment"
import "java.io.File"

local M = {}
M.storageDirectory = nil
M.workDirectory = nil

-- 获取存储目录
-- @return 获取外部存储目录，如果不存在则返回应用私有目录
M.getStorageDirectory=function(fileName)
  local dir = M.storageDirectory
  if fileName == nil then
    return dir
  end
  return File(dir, fileName)
end

-- 获取 App 工作文件夹
-- @return
M.getWorkDirectory=function(fileName)
  local dir = M.workDirectory
  if fileName == nil then
    return dir
  end
  return File(dir, fileName)
end

-- 执行模块初始化代码
-- 初始化常量
local WORKDIR_NAME = "AndroLua"
-- 存储目录
local storageDirectory = nil
if (Environment.MEDIA_MOUNTED == Environment.getExternalStorageState()) then
  storageDirectory = Environment.getExternalStorageDirectory()
else
  storageDirectory = context.getFilesDir()
end
M.storageDirectory = storageDirectory
-- 工作目录
local workDirectory = File(storageDirectory, WORKDIR_NAME)
M.workDirectory = workDirectory
if not workDirectory.exists() then
  workDirectory.mkdirs()
end

return M